LangString SNAP_TEXT_0 ${LANG_ENGLISH} "Welcome to SnapTrans"
LangString SNAP_TEXT_0 ${LANG_SIMPCHINESE} "欢迎使用 SnapTrans"
LangString SNAP_TEXT_1 ${LANG_ENGLISH} "Capture, recognize and translate in one workspace.$\r$\n$\r$\nThe app, models and personal data stay in your selected folder. No administrator access is needed. System integration and shortcuts are optional.$\r$\n$\r$\nChoose a writable folder. Exit the previous version from the tray before upgrading."
LangString SNAP_TEXT_1 ${LANG_SIMPCHINESE} "程序、模型、配置、密钥、日志和运行临时文件均保存在所选安装目录。无需管理员权限。$\r$\n$\r$\n默认不创建卸载注册项和系统快捷方式，直接打开安装目录中的 SnapTrans.exe 使用。系统集成和桌面快捷方式可选。$\r$\n$\r$\n请选择当前用户可写的文件夹。升级前请从托盘退出旧版。"
LangString SNAP_TEXT_2 ${LANG_ENGLISH} "Launch SnapTrans"
LangString SNAP_TEXT_2 ${LANG_SIMPCHINESE} "打开 SnapTrans"
LangString SNAP_TEXT_3 ${LANG_ENGLISH} "Remove SnapTrans and selected system integration. The data folder (settings, keys and logs) is retained. You can delete it manually when no longer needed."
LangString SNAP_TEXT_3 ${LANG_SIMPCHINESE} "卸载 SnapTrans 程序及所选的系统集成。安装目录内的 data（设置、密钥与日志）保留；不再需要时可自行删除。"
LangString SNAP_TEXT_4 ${LANG_ENGLISH} "The app and personal data stay in this folder. Choose a writable location, outside protected Program Files. Select the existing folder to upgrade. Windows records and installer temporary files are separate from app data."
LangString SNAP_TEXT_4 ${LANG_SIMPCHINESE} "安装到哪里，程序和个人数据就保存在那里。请选择可写目录；不要使用受保护的 Program Files。升级时选择原安装目录。Windows 自身的运行记录和安装器临时文件不属于应用数据。"
LangString SNAP_TEXT_5 ${LANG_ENGLISH} "Exit SnapTrans from the system tray before installing or uninstalling."
LangString SNAP_TEXT_5 ${LANG_SIMPCHINESE} "请先从系统托盘退出 SnapTrans，再继续安装或卸载。"
LangString SNAP_TEXT_6 ${LANG_ENGLISH} "The program is in use or not writable. Exit SnapTrans and check folder permissions."
LangString SNAP_TEXT_6 ${LANG_SIMPCHINESE} "程序文件正在使用或不可写。请先退出 SnapTrans，并检查安装目录权限。"
LangString SNAP_TEXT_7 ${LANG_ENGLISH} "Windows 10 / 11, 64-bit is required."
LangString SNAP_TEXT_7 ${LANG_SIMPCHINESE} "需要 Windows 10 / 11 64 位系统。"
LangString SNAP_TEXT_8 ${LANG_ENGLISH} "Another SnapTrans installer is running."
LangString SNAP_TEXT_8 ${LANG_SIMPCHINESE} "另一个 SnapTrans 安装程序正在运行。"
LangString SNAP_TEXT_9 ${LANG_ENGLISH} "A newer version ($0) is installed. Downgrading is not supported."
LangString SNAP_TEXT_9 ${LANG_SIMPCHINESE} "已安装较新版本 $0，不支持直接降级。"
LangString SNAP_TEXT_10 ${LANG_ENGLISH} "SnapTrans application (required)"
LangString SNAP_TEXT_10 ${LANG_SIMPCHINESE} "SnapTrans 程序（必需）"
LangString SNAP_TEXT_11 ${LANG_ENGLISH} "Cannot read the destination. Check permissions or choose another folder."
LangString SNAP_TEXT_11 ${LANG_SIMPCHINESE} "无法读取安装目录，请检查目录权限或选择其他文件夹。"
LangString SNAP_TEXT_12 ${LANG_ENGLISH} "Choose an empty folder. Keep existing portable versions and migrate their data after installing."
LangString SNAP_TEXT_12 ${LANG_SIMPCHINESE} "请选择空文件夹。已有便携版请保留原目录，安装后再按说明迁移 data。"
LangString SNAP_TEXT_13 ${LANG_ENGLISH} "This folder contains a newer version ($0). Downgrading is not supported."
LangString SNAP_TEXT_13 ${LANG_SIMPCHINESE} "此目录已有较新版本 $0，不支持直接降级。"
LangString SNAP_TEXT_14 ${LANG_ENGLISH} "Previous uninstall did not finish. Setup stopped without changing personal settings."
LangString SNAP_TEXT_14 ${LANG_SIMPCHINESE} "旧版卸载未完成，安装已停止。个人配置保持不变。"
LangString SNAP_TEXT_15 ${LANG_ENGLISH} "System integration (optional registry / Start menu)"
LangString SNAP_TEXT_15 ${LANG_SIMPCHINESE} "系统集成（卸载注册项和开始菜单，可不选）"
LangString SNAP_TEXT_16 ${LANG_ENGLISH} "Create desktop shortcut"
LangString SNAP_TEXT_16 ${LANG_SIMPCHINESE} "创建桌面快捷方式"
LangString SNAP_TEXT_17 ${LANG_ENGLISH} "Cannot verify the installation folder. Uninstall cancelled."
LangString SNAP_TEXT_17 ${LANG_SIMPCHINESE} "无法确认安装目录，已取消卸载。"
